#KerasJson: parkingModels/model2.json
KerasH5: saveZoo/model.h5
InputData: parkingModels/inputs.npy
OutputPredictions: parkingModels/outputs.npy
OutputDir: my-hls-test
ProjectName: myproject
XilinxPart: xc7z020clg400-1
# In ns
ClockPeriod: 5
Backend: Vivado

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<64, 32>
    ReuseFactor: 1
    Strategy: Latency
  LayerType:
    Dense:
      ReuseFactor: 1
      Precision: 
        weight: ap_fixed<64,32>
        bias: ap_fixed<64,32>
        result: ap_fixed<64, 32>
    Relu:
      ReuseFactor: 1
      Precision: 
#        weight: ap_fixed<16,4>
#        bias: ap_fixed<16,2>
        result: ap_fixed<64, 32>
#       Strategy: Resource
